class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    authenticate_user(AccountCredential::TYPES[:fb], request.env["omniauth.auth"])
  end

  def twitter
    authenticate_user(AccountCredential::TYPES[:tw], request.env["omniauth.auth"])
  end

  protected
  def after_omniauth_failure_path_for(scope)
    main_app.root_path
  end

  private

  def authenticate_user(type, omniauth)
    user = User.find_user(type, omniauth["uid"])
    user = store_account_credentials(type, omniauth) unless user
    if user && user.valid?
      sign_in(:user, user)
      flash[:notice] = "successfully logged in."
      redirect_to refinery.root_path
      return
    else
      flash[:alert] = user.errors.to_a.first
      redirect_to main_app.root_path
    end
  end

  def store_account_credentials(type, omniauth)
    email = (type == AccountCredential::TYPES[:tw]) ? User.autogenerated_twitter_email(omniauth["info"]["nickname"]) :
                                                      omniauth["info"]["email"]
    password = User.autogenerated_password
    user = User.new(email: email, password: password,
                    password_confirmation: password, first_name: omniauth["info"]["name"])
    acc = AccountCredential.new(uid: omniauth["uid"], account_type: type, token: omniauth["credentials"]["token"])
    acc.update_attributes(:token_secret => omniauth["credentials"]["secret"]) if type == AccountCredential::TYPES[:tw]
    if acc.valid? && user.save
      acc.save
      user.account_credentials <<  acc
    end
    user
  end
end

