class Users::RegistrationsController < Devise::RegistrationsController
  skip_before_filter :authenticate_user!

  def create
    render :json => register_with_email(params)
  end

  private
  # for later use
  # def register_with_social_network_account(params)
  #   social_network_acc = SocialNetworkCredential.new(params[:social_network_credential])
  #   params[:user][:password] = User.autogenerated_password
  #   params[:user][:password_confirmation] = params[:password]
  #   user = User.new(params[:user])
  #   # only save social_network_acc after user record is saved
  #   if social_network_acc.valid? && user.save
  #     social_network_acc.save
  #     user.social_network_credentials <<  social_network_acc
  #     { :success => true, :msg => I18n.t("registration.confirm", :user_email => user.email), :subdomain => user.get_domain }
  #   else
  #     { :success => false, :msg => user.get_errors }
  #   end
  # end

  def register_with_email(params)
    user = User.new(params[:user])
    if user.save
      { :success => true, :msg => "Please check your email #{user.email}. We have sent a confirmation instruction there.", :path => root_path}
    else
      { :success => false, :msg => user.get_errors }
    end
  end
end